### ISSUE TITLE
Typo in the qa prompt

### ISSUE THREAD

**Issue by zifken** [Haste171/langchain-chatbot#10]
Given the current version of the prompt : 
```python
QA_PROMPT = """You are a helpful AI assistant. Use the following pieces of context to answer the question at the end.
If you don't know the answer, just say you don't know. DO NOT try to make up an answer.
If the question is not related to the context, politely respond that you are tuned to only answer questions that are related to the context.
Use as much detail when as possible when responding.

{context}

Question: {question}
Helpful answer in markdown format:"""
```
I this there is a typo in the last line : `Use as much detail when as possible when responding.` it should be `Use as much detail as possible when responding.` 

Not sure if this affects the model behaviour.

**Comment by Haste171** [comment]
Thanks for noticing this,

If you would like to contribute to the LangChain Chatbot, please follow these steps:

Fork the repository
Create a new branch for your feature or bug fix
Write tests for your changes
Implement your changes and ensure that all tests pass
Submit a pull request
