### ISSUE TITLE
pinecone key not recognized

### ISSUE THREAD

**Issue by Valengou** [Haste171/langchain-chatbot#15]
Hi, when i paste the keys in the .env file it doesn't recognize pinecone one and then it tries to use chroma. When it use chroma, it says that no index was found,  and cannot answer the query do you know what the problem could be? Maybe something to do with the index dimension? Thanks

**Comment by Haste171** [comment]
This has happened to other users aswell, create a virtual environment and install all the requirements and create new keys in pinecone.

**Comment by Valengou** [comment]
I was doing 2 mistakes, 1 in the terminal i was using y instead of Y so it didn't recognize the comand. In the streamlit app i wasn't hiting enter when pasting my keys. Thanks!
