### ISSUE TITLE
I need to get the pinecone id

### ISSUE THREAD

**Issue by lonelytechpot** [Haste171/langchain-chatbot#21]
Hi everyone.
I need to get the pinecone data id using langchain but that  doesn't give the id.
How can I get it?
This is the code
```javascript
const embeddings = new OpenAIEmbeddings();
const index = pinecone.Index(process.env.PINECONE_INDEX ?? '');
const dbConfig = {
  pineconeIndex: index,
  namespace: process.env.PINECONE_NAMESPACE ?? '',
  textKey: PINECONE_TEXT_KEY,
};

const result = await PineconeStore.fromDocuments(output, embeddings, dbConfig);
```

**Comment by Haste171** [comment]
https://www.google.com/search?q=how+to+create+a+pinecone+account+and+get+api+key&oq=how+to+create+a+pinecone+account+and+get+api+key&aqs=chrome..69i57j33i160l5j33i299l2.4206j0j7&sourceid=chrome&ie=UTF-8#fpstate=ive&vld=cid:99a7e773,vid:_gC9wWWBjmY
