### ISSUE TITLE
chat history in streamlit doesn't seem to work

### ISSUE THREAD

**Issue by DennisPeeters** [Haste171/langchain-chatbot#23]
Hi,

When using streamlit I tried figuring out how to get the chat history to work. Every time I append the chat history it gets erased again. 

Any suggestions? 

grt

**Comment by Haste171** [comment]
Create a function that recursively adds chat history to an external json file as a make-shift database. Or wait until the website is finished sometime this weekend.

**Comment by DennisPeeters** [comment]
I actually found a way to make it work, can I send it to you?

**Comment by Haste171** [comment]
Yes, please make a pull request!

**Comment by Haste171** [comment]
Please review the recent changes.

**Comment by mw-hv** [comment]
> I actually found a way to make it work, can I send it to you?

@DennisPeeters Hi Dennis, could you share your workaround? Would love to learn, thanks.
