### ISSUE TITLE
It seems the template is not taken into account

### ISSUE THREAD

**Issue by DennisPeeters** [Haste171/langchain-chatbot#24]
What I did:
- Remove the cached versions of the templates (\templates\__pycache__)
- Changed the copy in qa_prompt.py for my specific project (in this case the bot needs to answer in dutch, providing this input in the template is useful in other experiments I did)
- Run the streamlit.py code

Expected result: 
- See a clear indication the the template is being processed and has an impact on the answer

Result:
- Same answers, it doesn't matter how hard I change the template. I tried to change the character, answer type,...

Any idea why this is the case?

**Comment by DennisPeeters** [comment]
Figured it out

Indeed, here is the full code I used

```
        # Define the system message template
        system_template = """End every answer with "Ahoi Maty I love you". Use the following pieces of context to answer the users question. 
        If you cannot find the answer from the pieces of context, just say that you don't know, don't try to make up an answer.
        ----------------
        {context}"""

        # Create the chat prompt templates
        messages = [
        SystemMessagePromptTemplate.from_template(system_template),
        HumanMessagePromptTemplate.from_template("{question}")
        ]
        qa_prompt = ChatPromptTemplate.from_messages(messages)
        st.write("qa_prompt", qa_prompt)
```

and then

`        qa = ConversationalRetrievalChain.from_llm(llm=model, retriever=retriever, return_source_documents=True,combine_docs_chain_kwargs={"prompt": qa_prompt})`

I am obviously not a developer, but it works (and I must say that the documentation on Langchain is very very difficult to follow)

**Comment by Haste171** [comment]
Please review the recent changes.
