### ISSUE TITLE
sh: cls: command not found

### ISSUE THREAD

**Issue by text2sql** [Haste171/langchain-chatbot#3]
thanks much for this. works great. but i am getting this error (macos) : sh: cls: command not found. 
still, it ingests and searches just fine

**Comment by Haste171** [comment]
Sorry, that's a bug with the way it clears the console for Windows only, on mac it would be `clear` I believe, located on line `35`

**Comment by text2sql** [comment]
Thank you! Is chat interface available yet? I see there is a snapshot :-)
