### ISSUE TITLE
HTML 

### ISSUE THREAD

**Issue by Mihaitafox11** [Haste171/langchain-chatbot#6]
You think this can be adapted to add scraped HTML code?

For example, scrape the documentation of a programming language and ask it to code based on that?

**Comment by Haste171** [comment]
> You think this can be adapted to add scraped HTML code?
> 
> 
> 
> For example, scrape the documentation of a programming language and ask it to code based on that?

Yes absolutely, Langchain already supports documentation loading and scraping so we will definitely add that in the future to the chat interface...
